# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerryToDoListDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~>4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.0'
  pod 'AlamofireImage', '~> 3.1'
  # Pods for PerryToDoListDemo

  target 'PerryToDoListDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PerryToDoListDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
